version: '3'

services:
  db:
    image: mongodb/mongodb-community-server:latest 
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      TZ: Asia/Seoul

  api:
    build: ./backend
    image: kbchat-api:latest
    ports:
      - 8088:8088
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./frontend
    image: kbchat-web:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
