"""init

Revision ID: d3fa00d2937a
Revises: c359c0561312
Create Date: 2025-03-22 22:39:27.225302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'd3fa00d2937a'
down_revision: Union[str, None] = 'c359c0561312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deposits', sa.Column('url', sa.String(), nullable=False),
        sa.Column('category', sa.Enum('예금', '적금', '입출금자유', '주택청약', name='depositcategoryenum'), nullable=False),
        sa.Column('title', sa.String(), nullable=False), sa.Column('period', sa.String(), nullable=True),
        sa.Column('amount', sa.String(), nullable=True), sa.Column('interest', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_table(
        'faqs', sa.Column('url', sa.String(), nullable=False),
        sa.Column(
            'category',
            sa.Enum('예금', '신탁/펀드', '대출', '환전/송금', '수출입', '외화예금/기타', '퇴직연금', name='faqcategoryenum'),
            nullable=False
        ), sa.Column('title', sa.String(), nullable=False),
        sa.Column('title_dense_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column('title_sparse_vector', pgvector.sqlalchemy.sparsevec.SPARSEVEC(dim=250002), nullable=True),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('content_dense_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column('content_sparse_vector', pgvector.sqlalchemy.sparsevec.SPARSEVEC(dim=250002), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_table(
        'loans', sa.Column('url', sa.String(), nullable=False),
        sa.Column(
            'category',
            sa.Enum('신용대출', '담보대출', '전월세/반환보증', '자동차대출', '집단중도금/이주비대출', '주택도시기금대출', name='loancategoryenum'),
            nullable=False
        ), sa.Column('title', sa.String(), nullable=False), sa.Column('target', sa.String(), nullable=True),
        sa.Column('period', sa.String(), nullable=True), sa.Column('repayment_method', sa.String(), nullable=True),
        sa.Column('limit', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_table(
        'deposit_content_chunks', sa.Column('deposit_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('dense_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column('sparse_vector', pgvector.sqlalchemy.sparsevec.SPARSEVEC(dim=250002), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_deposit_content_chunks_deposit_id'), 'deposit_content_chunks', ['deposit_id'], unique=False
    )
    op.create_table(
        'loan_content_chunks', sa.Column('loan_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('dense_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column('sparse_vector', pgvector.sqlalchemy.sparsevec.SPARSEVEC(dim=250002), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_content_chunks_loan_id'), 'loan_content_chunks', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_content_chunks_loan_id'), table_name='loan_content_chunks')
    op.drop_table('loan_content_chunks')
    op.drop_index(op.f('ix_deposit_content_chunks_deposit_id'), table_name='deposit_content_chunks')
    op.drop_table('deposit_content_chunks')
    op.drop_table('loans')
    op.drop_table('faqs')
    op.drop_table('deposits')
    # ### end Alembic commands ###
