"""description column 추가

Revision ID: e2c092a8a75a
Revises: d3fa00d2937a
Create Date: 2025-03-23 00:09:26.734355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c092a8a75a'
down_revision: Union[str, None] = 'd3fa00d2937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('description', sa.String(), nullable=False))
    op.add_column('loans', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'description')
    op.drop_column('deposits', 'description')
    # ### end Alembic commands ###
